name: friendhub
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.18
  font_awesome_flutter: ^10.4.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:
  assets:
    - assets/logo.png
    - assets/pfp/mikha.jpg
    - assets/pfp/aiah.jpg
    - assets/pfp/colet.jpg
    - assets/pfp/maloi.jpg
    - assets/pfp/gwen.jpg
    - assets/pfp/stacey.jpg
    - assets/pfp/jhoanna.jpg
    - assets/pfp/sheena.jpg
    - assets/pfp/pfp.jpg
    - assets/pfp/taylor.jpg
    - assets/pfp/katy.jpg
    - assets/pfp/renz.jpg
    - assets/pfp/david.jpg
    - assets/pfp/kath.jpg
    - assets/pfp/roseann.jpg
    - assets/pfp/carlo.jpg
    - assets/pfp/kier.jpg
    - assets/pfp/martin.jpg
    - assets/pfp/renz.jpg
    - assets/pfp/kate.jpg
    - assets/pfp/anna.jpg
    - assets/pfp/maria.jpg
    - assets/pfp/sofia.jpg
    - assets/pfp/andrea.jpg
    - assets/pfp/kristine.jpg
    - assets/pfp/grace.jpg
    - assets/pfp/isabella.jpg
    - assets/post/poststacey.jpg
    - assets/post/postmaloi.jpg
    - assets/post/postsheena.jpg
    - assets/post/postgwen.jpg
    - assets/post/postjho.jpg
    - assets/post/postkier.jpg
    - assets/post/postkier2.jpg
    - assets/post/postkier3.jpg
    - assets/post/postmartin.jpg
    - assets/pfp/coverprofile.jpg
    - assets/videopost/post1.mp4
    - assets/videopost/post2.mp4
    - assets/videopost/post3.mp4
    - assets/videopost/post4.mp4
    - assets/videopost/post5.mp4
    - assets/videopost/post6.mp4

  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400

    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
